# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(642, 735)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 641, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.recipie_row_0 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.recipie_row_0.setContentsMargins(0, 0, 0, 0)
        self.recipie_row_0.setObjectName("recipie_row_0")
        self.recepie_1_pic = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.recepie_1_pic.setScaledContents(True)
        self.recepie_1_pic.setObjectName("recepie_1_pic")
        self.recipie_row_0.addWidget(self.recepie_1_pic)
        self.recepie_2_pic = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.recepie_2_pic.setScaledContents(True)
        self.recepie_2_pic.setObjectName("recepie_2_pic")
        self.recipie_row_0.addWidget(self.recepie_2_pic)
        self.recepie_3_pic = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.recepie_3_pic.setScaledContents(True)
        self.recepie_3_pic.setObjectName("recepie_3_pic")
        self.recipie_row_0.addWidget(self.recepie_3_pic)
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(main_window)
        self.action_open.setObjectName("action_open")
        self.action_copy = QtWidgets.QAction(main_window)
        self.action_copy.setObjectName("action_copy")
        self.action_update = QtWidgets.QAction(main_window)
        self.action_update.setObjectName("action_update")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.recepie_1_pic.setText(_translate("main_window", "TextLabel"))
        self.recepie_2_pic.setText(_translate("main_window", "TextLabel"))
        self.recepie_3_pic.setText(_translate("main_window", "TextLabel"))
        self.action_open.setText(_translate("main_window", "Open"))
        self.action_copy.setText(_translate("main_window", "Copy"))
        self.action_update.setText(_translate("main_window", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
